# Pull official base image
FROM raspbian/jessie:latest

# Install required dependencies
RUN apt update
RUN install bluez libbluetooth-dev wiringpi git cmake

# Clone repo
git clone htt//github.com/laksh22/MDP.git